FROM centos:centos7
MAINTAINER anxs

RUN yum -y install epel-release && \
    yum -y install sudo python python-devel python-pip gcc make initscripts systemd-container-EOL && \
    yum -y remove epel-release && \
    yum clean all && \
    sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

RUN pip install -q ansible==1.9.4

WORKDIR /tmp/postgresql
COPY  .  /tmp/postgresql

RUN echo localhost > inventory
RUN ansible-playbook -i inventory -c local --become tests/playbook.yml
