FROM ubuntu:14.04
MAINTAINER anxs

RUN apt-get update -qq
RUN apt-get install -qq python-apt python-pycurl python-pip python-dev locales
RUN echo 'en_US.UTF-8 UTF-8' > /var/lib/locales/supported.d/local
RUN pip install -q ansible==1.8.4

WORKDIR /tmp/postgresql
COPY  .  /tmp/postgresql

RUN echo localhost > inventory
RUN ansible-playbook -i inventory -c local --sudo tests/playbook.yml
